<?php
class Cookies
{
    function check_cookie($cookie_path, $cookie_name)
    {
		//Remove path for root directory cookies
		if(!isset($_COOKIE[$cookie_name]))
			return false;
		else
			return $_COOKIE[$cookie_name];
		return;
	}

	function set_cookie_($cookie_name, $value, $project)
	{
		setcookie($cookie_name, $value, time() + (86400 * 30), $this->cookie_path($project) . "; samesite=strict");
		return;
	}
	
	function renew_cookie($cookie_name, $project)
	{
		$cookie = $this->check_cookie("/", $cookie_name);
		$this->set_cookie_($cookie_name, $cookie, $project);
		return;
	}
	
	function cookie_path($project)
	{
		return "/";
	}
	
	function cookie_dialog($text, $doc, $onaccept, $onnotaccept)
	{
		//Warning cookies will not be generated by this file, you will have to generate accepted cookies cookie on your own
		echo "<div class=\"cookies_background\" id=\"cookies_background\"><div class=\"cookies\" id=\"cookies\"><label>".$text." <a href=\"".$doc."\" target=\"new\"><label  class=\"cookies_learn\">Click here to learn more..</label></a></label><br><br><a href=\"".$onaccept."\"><button class=\"cookie_button\">I accept</button></a><a href=\"".$onnotaccept."\"><button class=\"cookie_button\">I do not accept</button></a></div></div>";
		return;
	}
}
?>
