<?php
class Cookies
{
    function check_cookie($cookie_path, $cookie_name)
    {
		//Remove path for root directory cookies
		if(!isset($_COOKIE[$cookie_name]))
			return false;
		else
			return $_COOKIE[$cookie_name];
		return;
	}
	
    function check_cookie_wpath($cookie_path, $cookie_name)
    {
		//Remove path for root directory cookies
		if(!isset($_COOKIE[$cookie_path . $cookie_name]))
			return false;
		else
			return $_COOKIE[$cookie_path . $cookie_name];
		return;
	}

	function set_cookie_($cookie_name, $value, $project, $domain)
	{
		//Check if php 7.2 or 7.3
		if (version_compare(PHP_VERSION, '7.3.0', '<'))
			setcookie($cookie_name, $value, time() + (86400 * 30), $this->cookie_path($project) . "; samesite=strict");
		else
			//setcookie ($cookie_name, $value, time() + (86400 * 30), $this->cookie_path($project), $domain, false, false);
			setcookie($cookie_name, $value, [
				'expires' => time() + (86400 * 3),
				'path' => /*$this->cookie_path($project)*/'/',
				'domain' => $domain,
				'secure' => true,
				'httponly' => true,
				'samesite' => 'Strict',
			]);
		return;
	}
	
	function renew_cookie($cookie_name, $project, $domain)
	{
		$cookie = $this->check_cookie("/", $cookie_name);
		$this->set_cookie_($cookie_name, $cookie, $project, $domain);
		return;
	}
	
	function cookie_path($project)
	{
		return "/" . $project;
	}
	
	function cookie_dialog($text, $doc, $onaccept, $onnotaccept)
	{
		//Warning cookies will not be generated by this file, you will have to generate accepted cookies cookie on your own
		echo "<div class=\"cookies_background\" id=\"cookies_background\"><div class=\"cookies\" id=\"cookies\"><label>".$text." <a href=\"".$doc."\" target=\"new\"><label  class=\"cookies_learn\">Click here to learn more..</label></a></label><br><br><a target=\"new\" href=\"".$onaccept."\"><button class=\"cookie_button\" onclick=\"setTimeout(location.reload.bind(location), 2000);\">I accept</button></a><a target=\"new\" href=\"".$onnotaccept."\"><button class=\"cookie_button\" onclick=\"setTimeout(location.reload.bind(location), 2000);\">I do not accept</button></a></div></div>";
		return;
	}
}
?>
